### ISSUE TITLE
Slight incorrect transparency on some icons on Vivid-Dark-Plasma theme

### ISSUE THREAD

**Issue by queenbiscuit311** [L4ki/Vivid-Plasma-Themes#1]
This theme is wonderful, but I have noticed that a few of the icons here have a slight noticeable partially opaque background. Here are the ones that I could find:

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/60015021-f141-40f5-b2f3-600158fc208d)

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/2a5f0a9a-57d3-4257-be7f-d293387ac5e7)

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/3fcb7aee-24b7-417f-b0b9-f1dc69b47f0e)

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/5e348768-6e23-4b63-86f9-52e97c7b50b4)

I don't believe any of the other icons have this issue but I'm not 100% sure

For comparison: here's an icon without this background:

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/8358f399-5394-48d4-9ed3-cb737d1d0a8d)

**Comment by L4ki** [comment]
Hi queenbiscuit311,

You have around the falcon. Thank You. The next update will be in 5 days, and I'll fix it.
Thanks again.

Greetings,

**Comment by queenbiscuit311** [comment]
forgot to update this. this does appear to be fixed. thank you!

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/2f7be167-aace-44c9-8624-b2053c6616e7)

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/f7e574da-f6b9-4179-8e66-f880a4b8371f)

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/ffe48e3c-c086-4f92-9c10-66b80f6ef8af)

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/ccb2b0d5-0bec-400c-87bd-576db7dd6d2f)

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/88851292/87e30e19-877a-4543-b0b3-b51c2fbdfc7b)
