### ISSUE TITLE
sddm theme not working

### ISSUE THREAD

**Issue by DaRandomCube** [L4ki/Vivid-Plasma-Themes#3]
when I return to the login screen, the default sddm theme shows an error message: type battery not available, and module org.kde.plasma.workspace.component
I've made sure that plasma-framework is installed, still doesn't help

**Comment by L4ki** [comment]
Hi DaRandomCube, 

Do you use Plasma 5 or 6?

**Comment by exstntlmsnthrp** [comment]
I have issues with SDDM theme as well. I've updated to Plasma 6.

The errors (yes, multiple) tell me the following are not installed, when the related packages are already installed.

```
org.kde.plasma.core
org.kde.plasma.extras
org.kde.plasma.components
```

**Comment by DaRandomCube** [comment]
plasma 6
not compatible ?

**Comment by L4ki** [comment]
I'm working on taking it to Plasma 6, but I have some problems I'm trying to solve.

**Comment by L4ki** [comment]
The SDDM Theme was added, which is tailored for Plasma 6
