### ISSUE TITLE
Some toolbar icons get showed as X

### ISSUE THREAD

**Issue by warcayac** [L4ki/Vivid-Plasma-Themes#4]
Your icons are beautiful but it seems to not work well for all apps like Pinta:

![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/7342885/9643de2c-353d-4f48-855e-e3b27c9d8407)

My OS info:

OS: EndeavourOS Linux x86_64
Kernel: 6.7.9-zen1-1-zen
Shell: zsh 5.9
Resolution: 3440x1440
DE: Plasma 6.0.1 ( X11 )
WM: KWin
Theme: Vivid-Dark-GTK [GTK2/3]
Icons: Vivid-Dark-Icons [GTK2/3]
Terminal: WarpTerminal
CPU: AMD Ryzen 7 1700 (16) @ 3.800GHz
GPU: NVIDIA GeForce GTX 1070
Memory: 15905MiB

This doesn't happen with other Icons Themes

**Comment by L4ki** [comment]
Hi warcayac,

I don't know why it's like that with you. 

It looks like this to me:

![Screenshot_20240315_201104](https://github.com/L4ki/Vivid-Plasma-Themes/assets/45247573/9bbc7050-ad39-4c73-ab31-d3bd4b536653)

**Comment by warcayac** [comment]
I've applied your global theme and theme for Kvantum, but the same problem, [this link](https://drive.google.com/file/d/1SciBvw_5RjsB4pAIQWbqZ5z-nbvsiEZQ/view?usp=drive_link) is a video.

Another question is the blur is not applied, only transparency. Maybe I'm missing some configuration. Can you make a step-by-step guide, please?. Your floating panel is interesting also.

another problem that was not shown in the video is about icons size, after rebooting my PC icons are shown very small, I need to change global theme and return to previous theme for that icons recover its normal size, but it lasts for current session only.

**Comment by warcayac** [comment]
icons theme received an update and the problem was resolved respect icons showing an X. Regarding small icons when applying global theme, I'm applying default theme and for the rest I'm applying Vivid. Regarding blur effect is pending about how to enable it
