### ISSUE TITLE
Blueish circles around Decoration buttons

### ISSUE THREAD

**Issue by Diyou** [L4ki/Vivid-Plasma-Themes#5]
Love the themes but I noticed some blueish circles around the decoration buttons when hovering like:
![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/21966966/6b838a9b-d50d-4f07-95b0-f177dd453b34)
or 
![image](https://github.com/L4ki/Vivid-Plasma-Themes/assets/21966966/6ca3eb68-d52e-49e8-bcb4-282788b6dbcb)

**Comment by L4ki** [comment]
Hi Diyou, 

Thank you, I will correct that.
